name: aichatbot

services: 
  webapp-dev:
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: dev
    ports:
      - 3000:3000
    volumes: 
      - ../src:/webapp

  webapp-build:
    build:
      context: .
      target: build
    volumes:
      - ../src:/webapp
    command: ["npm", "run", "build"]
  
  # webapp-run:
  #   build:
  #     context: .
  #     target: runner
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=runner
